-- ============================================================================
-- ORIGIN — Seed: 237 real Cameroon tourism / heritage sites (idempotent)
-- ----------------------------------------------------------------------------
-- Researched from public web sources. image_url = REAL free Wikipedia /
-- Wikimedia lead image when the site has one (114/237 sites). The web app
-- shows a clean on-brand placeholder for the rest — NEVER a random/unrelated image.
-- Self-sufficient (adds the image_url column) + idempotent. Run in Supabase SQL Editor.
-- ============================================================================

ALTER TABLE "tourism_places" ADD COLUMN IF NOT EXISTS "image_url" VARCHAR(500);

WITH admin AS (
  SELECT id FROM accounts WHERE phone_number = '+237655922472' LIMIT 1
),
data(name, description, region, category, lat, lng, image_url) AS (
  VALUES
  ('Mont Cameroun', 'Plus haut sommet d''Afrique de l''Ouest, ce volcan actif de 4 095 m domine l''océan et offre une ascension légendaire à travers forêts et coulées de lave.', 'Sud-Ouest', 'NATURE', 4.2167, 9.1725, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Cameroon_view_from_Buea_(Soppo).jpg'),
  ('Parc national de Korup', 'L''une des plus anciennes et plus riches forêts tropicales d''Afrique, traversée par le célèbre pont suspendu sur la rivière Mana.', 'Sud-Ouest', 'NATURE', 5.083, 8.833, 'https://commons.wikimedia.org/wiki/Special:FilePath/Korup_National_park.jpg'),
  ('Jardin botanique de Limbe', 'Fondé en 1892, ce jardin verdoyant au bord de l''Atlantique abrite des milliers d''espèces tropicales et un superbe jardin de la jungle.', 'Sud-Ouest', 'NATURE', 4.0167, 9.2167, 'https://commons.wikimedia.org/wiki/Special:FilePath/Garden_Information_Center_-_Limbe_Botanic_Garden.jpg'),
  ('Centre de la faune de Limbe', 'Sanctuaire de primates où gorilles, chimpanzés et drills sauvés de la captivité retrouvent une vie paisible face à la mer.', 'Sud-Ouest', 'NATURE', 4.018, 9.211, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Limbe_Wildlife_Centre_exterior.JPG/960px-Limbe_Wildlife_Centre_exterior.JPG'),
  ('Down Beach de Limbe', 'Plage de sable volcanique noir où les pirogues colorées des pêcheurs rentrent au coucher du soleil sous le regard du Mont Cameroun.', 'Sud-Ouest', 'NATURE', 4.018, 9.218, 'https://commons.wikimedia.org/wiki/Special:FilePath/DOWN_BEACH_LIMBE_CAMEROON.jpg'),
  ('Plage de sable noir de Bakingili', 'Étendue spectaculaire de sable noir né des éruptions du Mont Cameroun, baignée par les vagues sauvages de l''Atlantique.', 'Sud-Ouest', 'NATURE', 4.083, 9.05, NULL),
  ('Debundscha', 'L''un des endroits les plus pluvieux du monde, où la forêt luxuriante dévale jusqu''à une côte battue par les flots au pied du volcan.', 'Sud-Ouest', 'NATURE', 4.0986, 9.025, NULL),
  ('Site historique de Bimbia', 'Ancien port négrier poignant, mémoire vive de la traite atlantique où subsistent les vestiges des cachots tournés vers l''océan.', 'Sud-Ouest', 'HERITAGE', 3.9539, 9.245, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bimbia_Slave_Port.jpg'),
  ('Résidence von Puttkamer de Buea', 'Élégant château allemand de l''époque coloniale, ancienne demeure du gouverneur, perché sur les flancs verdoyants de Buea.', 'Sud-Ouest', 'HERITAGE', 4.1667, 9.2333, 'https://commons.wikimedia.org/wiki/Special:FilePath/Schloss_von_Puttkamer.jpg'),
  ('Fontaine Bismarck de Buea', 'Monument colonial allemand niché dans la brume de Buea, témoin du passé où la ville fut capitale du Kamerun.', 'Sud-Ouest', 'HERITAGE', 4.1667, 9.2333, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bismarck_Fountain,_Buea.jpg'),
  ('Plantations de thé de Tole', 'Collines ondulantes tapissées de théiers d''un vert éclatant au pied du Mont Cameroun, paradis pour une promenade matinale.', 'Sud-Ouest', 'CULTURE', 4.1, 9.25, NULL),
  ('Mont Etinde', 'Surnommé le Petit Mont Cameroun, ce cône volcanique couvert de forêt primaire offre des panoramas saisissants sur la côte.', 'Sud-Ouest', 'NATURE', 4.1, 9.12, 'https://commons.wikimedia.org/wiki/Special:FilePath/View_of_Mt_Etinde.jpg'),
  ('Monument Alfred Saker de Limbe', 'Statue honorant le missionnaire fondateur de Limbe en 1858, gardienne de l''histoire de cette ville côtière pionnière.', 'Sud-Ouest', 'HERITAGE', 4.017, 9.215, 'https://commons.wikimedia.org/wiki/Special:FilePath/Alfred_Saker_monument.jpg'),
  ('Lac de cratère Barombi Mbo', 'Lac de cratère d''une eau turquoise entouré d''une forêt dense près de Kumba, abritant des espèces de poissons uniques au monde.', 'Sud-Ouest', 'NATURE', 4.6586, 9.4017, NULL),
  ('Mont Kupe', 'Montagne sacrée enveloppée de brumes, royaume des oiseaux rares et des légendes, paradis des ornithologues et des randonneurs.', 'Sud-Ouest', 'NATURE', 4.8, 9.683, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Statue_of_Kupe%2C_Wellington_Waterfront.jpg/960px-Statue_of_Kupe%2C_Wellington_Waterfront.jpg'),
  ('Lacs jumeaux du Manengouba', 'Deux lacs de cratère, le Lac Mâle et le Lac Femelle, nichés dans la caldeira herbeuse des hauts plateaux du Manengouba.', 'Sud-Ouest', 'NATURE', 5.0167, 9.8333, NULL),
  ('Parc national de Bakossi', 'Vaste sanctuaire de forêt de montagne et de cascades, l''un des plus riches en biodiversité d''Afrique, refuge de primates et d''amphibiens rares.', 'Sud-Ouest', 'NATURE', 4.92, 9.62, NULL),
  ('Réserve de faune de Banyang-Mbo', 'Forêt tropicale préservée où éléphants de forêt, chimpanzés et drills évoluent dans un décor d''une luxuriance intacte.', 'Sud-Ouest', 'NATURE', 5.38, 9.43, NULL),
  ('Mamfe et la vallée de la Cross River', 'Ville carrefour aux portes du Nigeria, point de départ vers les forêts vierges et les eaux sinueuses de la Cross River.', 'Sud-Ouest', 'CULTURE', 5.75, 9.31, NULL),
  ('Palais des Fons de Bafut', 'Joyau classé au patrimoine de l''UNESCO, ce palais sacré aux toitures coniques est le cœur vivant du royaume Bafut depuis des siècles.', 'Nord-Ouest', 'CHEFFERIE', 6.1, 10.1, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bafut_Palace_-_EcoVillage_-_Cameroon.JPG'),
  ('Musée de Bafut', 'Au sein de la chefferie, ce musée dévoile masques, trônes et regalia royaux qui racontent la riche culture des Grassfields.', 'Nord-Ouest', 'MUSEUM', 6.1, 10.1, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mus%C3%A9e_de_Bafut.jpg'),
  ('Palais et Musée de Mankon', 'Chefferie raffinée de Bamenda dont le musée primé expose un trésor d''art royal, de coiffes et d''objets sacrés des Tikar.', 'Nord-Ouest', 'CHEFFERIE', 5.96, 10.13, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mankon_Palace_(3).JPG'),
  ('Chefferie de Bali Nyonga', 'Royaume Chamba célèbre pour son éclatant festival Lela, où cavaliers et danseurs en costumes flamboyants honorent le Fon.', 'Nord-Ouest', 'CHEFFERIE', 5.8833, 10.0167, NULL),
  ('Palais du Fon de Nso à Kumbo', 'Siège du puissant royaume Nso, la chefferie de Kumbo perpétue traditions, cavalcades et le grand festival annuel des plantations.', 'Nord-Ouest', 'CHEFFERIE', 6.2, 10.67, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Tobin_View_of_the_Cathedral.JPG/960px-Tobin_View_of_the_Cathedral.JPG'),
  ('Palais de Laikom (royaume Kom)', 'Perché sur un éperon rocheux, l''antique palais du Fon de Kom veille sur des vallées vertigineuses et des traditions millénaires.', 'Nord-Ouest', 'CHEFFERIE', 6.27, 10.28, NULL),
  ('Chefferie de Big Babanki (Kedjom Keku)', 'Village des Grassfields aux maisons traditionnelles et à l''artisanat réputé, gardien d''une culture montagnarde authentique.', 'Nord-Ouest', 'CHEFFERIE', 6.1, 10.27, NULL),
  ('Musée de Babungo', 'À Ndop, ce musée renommé célèbre la métallurgie et la sculpture du royaume Vengo à travers une collection d''art exceptionnelle.', 'Nord-Ouest', 'MUSEUM', 6.05, 10.52, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sculptures_found_in_the_Babungo_Museum.jpg/960px-Sculptures_found_in_the_Babungo_Museum.jpg'),
  ('Lac Nyos', 'Lac de cratère d''un bleu profond aux montagnes spectaculaires, tristement célèbre pour l''éruption gazeuse de 1986, aujourd''hui apaisé.', 'Nord-Ouest', 'NATURE', 6.4381, 10.2989, 'https://commons.wikimedia.org/wiki/Special:FilePath/Nyos_Lake.jpg'),
  ('Lac Oku', 'Lac de cratère sacré niché à 2 200 m d''altitude dans la forêt de Kilum, miroir paisible entouré de sommets verdoyants.', 'Nord-Ouest', 'NATURE', 6.1928, 10.4539, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lake_Oku_Cameroon.jpg'),
  ('Lac Awing', 'Lac de cratère serein blotti dans les hauteurs au sud de Bamenda, entouré de villages et de paysages volcaniques verdoyants.', 'Nord-Ouest', 'NATURE', 5.95, 10.27, NULL),
  ('Chutes de la Menchum', 'Cascade tonitruante où la rivière Menchum se précipite dans une gorge spectaculaire, l''une des plus belles chutes du Cameroun.', 'Nord-Ouest', 'NATURE', 6.2648, 10.0398, 'https://commons.wikimedia.org/wiki/Special:FilePath/Menchum_Falls_NWprovince_Cameroon.jpg'),
  ('Parc national de Kimbi-Fungom', 'Mosaïque de savanes, galeries forestières et collines au nord de Wum, refuge d''antilopes, de buffles et d''une avifaune foisonnante.', 'Nord-Ouest', 'NATURE', 6.6, 10.25, NULL),
  ('Réserve de chasse du cratère de Mbi', 'Caldeira marécageuse nichée dans les hauts plateaux, sanctuaire d''oiseaux migrateurs et de paysages de cratère d''une rare beauté.', 'Nord-Ouest', 'NATURE', 6.07, 10.31, NULL),
  ('Forêt de Kilum-Ijim (Mont Oku)', 'Plus vaste forêt de montagne afromontagnarde restante d''Afrique de l''Ouest, royaume du touraco de Bannerman et des scommunités d''apiculteurs.', 'Nord-Ouest', 'NATURE', 6.2, 10.5, NULL),
  ('Collines de Sabga', 'Cols vallonnés où les éleveurs Mbororo mènent leurs troupeaux, offrant des panoramas saisissants sur les hautes terres de Bamenda.', 'Nord-Ouest', 'NATURE', 6.08, 10.32, NULL),
  ('Plantations de thé de Ndawara', 'Immense domaine théier déroulant ses collines vert émeraude sur les hauteurs de Boyo, spectacle agricole parmi les plus saisissants du pays.', 'Nord-Ouest', 'CULTURE', 6.32, 10.22, NULL),
  ('Bamenda et son Up Station', 'Capitale animée des Grassfields, célèbre pour la vue plongeante depuis l''escarpement d''Up Station sur la ville et la plaine.', 'Nord-Ouest', 'OTHER', 5.9614, 10.1517, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamenda_from_mountain_road.jpg'),
  ('Commercial Avenue de Bamenda', 'Artère commerçante palpitante au cœur de Bamenda, vitrine colorée du commerce, de l''artisanat et de la vie urbaine du Nord-Ouest.', 'Nord-Ouest', 'CULTURE', 5.96, 10.15, 'https://commons.wikimedia.org/wiki/Special:FilePath/Commercial_Avenue,_Bamenda,_Cameroon.jpg'),
  ('Cathédrale et mission de Shisong (Kumbo)', 'Haut lieu catholique fondé par les missionnaires sur les hauteurs de Nso, alliant ferveur religieuse et patrimoine historique.', 'Nord-Ouest', 'RELIGIOUS', 6.18, 10.68, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Tobin_View_of_the_Cathedral.JPG/960px-Tobin_View_of_the_Cathedral.JPG'),
  ('Palais Royal des Bamoun (Foumban)', 'Joyau de l''art bamoun, ce somptueux palais bâti par le sultan Njoya veille sur cinq siècles d''histoire royale.', 'Ouest', 'CHEFFERIE', 5.7256, 10.8987, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamun_sultan_palace.jpg'),
  ('Musée du Palais des Rois Bamoun', 'Trônes perlés, masques et armes royales racontent la grandeur de la dynastie Bamoun au cœur de Foumban.', 'Ouest', 'MUSEUM', 5.7258, 10.899, 'https://commons.wikimedia.org/wiki/Special:FilePath/Foumban-Museum1.jpg'),
  ('Rue des Artisans de Foumban', 'Sculpteurs sur bois, bronziers et brodeurs perpétuent ici le génie créatif légendaire du peuple Bamoun.', 'Ouest', 'CULTURE', 5.725, 10.8995, NULL),
  ('Grande Mosquée de Foumban', 'Élégante silhouette face au palais, elle témoigne de l''islam ancré dans la cité des sultans Bamoun.', 'Ouest', 'RELIGIOUS', 5.7253, 10.8983, NULL),
  ('Festival Nguon de Foumban', 'Tous les deux ans, le peuple juge son roi lors de ce rituel millénaire classé au patrimoine de l''UNESCO.', 'Ouest', 'CULTURE', 5.7256, 10.8987, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Chefferie de Bandjoun', 'Ses grandes cases coiffées de chaume et ornées de poteaux sculptés incarnent l''âme de la culture Bamiléké.', 'Ouest', 'CHEFFERIE', 5.3622, 10.4178, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandjoun_palace.jpg'),
  ('Musée de la chefferie de Bandjoun', 'Près de 400 objets rituels dévoilent les secrets, les sociétés et les rites du royaume Bandjoun.', 'Ouest', 'MUSEUM', 5.3625, 10.418, 'https://commons.wikimedia.org/wiki/Special:FilePath/MUSEE_de_la_chefferie_Bandjoun.jpg'),
  ('Chefferie supérieure de Bafoussam', 'Cœur spirituel de la cité, cette chefferie influente rayonne sur des dizaines de villages du pays Bamiléké.', 'Ouest', 'CHEFFERIE', 5.4781, 10.4179, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bafoussam_chefferie.JPG'),
  ('Chefferie de Batoufam', 'Labyrinthe de cours, de cases sculptées et de forgerons, ce palais vivant invite au voyage dans le temps.', 'Ouest', 'CHEFFERIE', 5.2667, 10.45, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chefferie_batoufam.jpg'),
  ('Musée Royal de Batoufam', 'La case du peuple et la cour centrale révèlent l''art de vivre et la mémoire du royaume de Batoufam.', 'Ouest', 'MUSEUM', 5.2669, 10.4503, 'https://commons.wikimedia.org/wiki/Special:FilePath/Entrée_du_musée_Royal_de_Batoufam.jpg'),
  ('Chefferie de Bana', 'Gardée par son lion de bronze et ses statues de chefs, Bana veille fièrement sur les hauteurs du Haut-Nkam.', 'Ouest', 'CHEFFERIE', 5.15, 10.2833, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chefferie_Bana.jpg'),
  ('Chefferie de Bamendjou', 'Alliance d''ancestralité et de modernité, ce palais des Hauts-Plateaux séduit par ses ornements perlés.', 'Ouest', 'CHEFFERIE', 5.4167, 10.3, NULL),
  ('Chefferie de Bangoua', 'Réputée pour ses danses masquées et ses cases ancestrales, Bangoua perpétue les traditions du Ndé.', 'Ouest', 'CHEFFERIE', 5.1833, 10.55, NULL),
  ('Chefferie de Baham', 'Ce royaume des Hauts-Plateaux conserve un riche patrimoine de cases sacrées et de trésors royaux.', 'Ouest', 'CHEFFERIE', 5.2667, 10.3667, NULL),
  ('Chefferie de Bandenkop', 'Niché dans les collines, ce palais Bamiléké enchante par son architecture et ses cérémonies colorées.', 'Ouest', 'CHEFFERIE', 5.3, 10.4, NULL),
  ('Chefferie de Bayangam', 'Entre cases à palabres et forêts sacrées, Bayangam dévoile la spiritualité profonde des Grassfields.', 'Ouest', 'CHEFFERIE', 5.3333, 10.45, NULL),
  ('Chefferie de Bangou', 'Ce royaume verdoyant des Hauts-Plateaux garde vivantes les danses et les rites de succession Bamiléké.', 'Ouest', 'CHEFFERIE', 5.2167, 10.3333, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Carrefour_Bangou.jpg/960px-Carrefour_Bangou.jpg'),
  ('Chefferie de Bandrefam', 'Petit royaume du Koung-Khi, Bandrefam séduit par ses cases traditionnelles et son accueil chaleureux.', 'Ouest', 'CHEFFERIE', 5.3, 10.47, NULL),
  ('Chefferie de Bangangté', 'Capitale du Ndé, ce royaume marie héritage Bamiléké et dynamisme d''une cité au charme authentique.', 'Ouest', 'CHEFFERIE', 5.15, 10.5167, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Bangangte_Marche_A.PNG/960px-Bangangte_Marche_A.PNG'),
  ('Chefferie de Bazou', 'Au cœur des collines du Ndé, Bazou cultive ses traditions et la mémoire de ses chefs ancestraux.', 'Ouest', 'CHEFFERIE', 5.1, 10.4667, NULL),
  ('Chefferie de Bafou', 'L''une des plus vastes chefferies de la Menoua, Bafou impressionne par ses paysages et ses cases royales.', 'Ouest', 'CHEFFERIE', 5.55, 10.1, NULL),
  ('Chefferie de Foto', 'Aux portes de Dschang, ce royaume verdoyant veille sur les hauts plateaux brumeux de la Menoua.', 'Ouest', 'CHEFFERIE', 5.45, 10.1, NULL),
  ('Chefferie de Foréké-Dschang', 'Ses cases sculptées et ses rites ancestraux font de Foréké-Dschang un haut lieu de la culture Bamiléké.', 'Ouest', 'CHEFFERIE', 5.42, 10.05, 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Pont_du_Plaisir.jpg'),
  ('Chefferie de Balatchi', 'Perchée dans les Bamboutos, Balatchi déploie ses cases traditionnelles face à des panoramas grandioses.', 'Ouest', 'CHEFFERIE', 5.65, 10.25, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Cameroun_from_a_village_balatchi.jpg/960px-Cameroun_from_a_village_balatchi.jpg'),
  ('Chefferie de Bamendou', 'Ce royaume de la Menoua conserve un précieux patrimoine de cases royales et de masques sacrés.', 'Ouest', 'CHEFFERIE', 5.5, 10.2, NULL),
  ('Chefferie de Baleng', 'Gardienne du célèbre lac sacré, Baleng allie spiritualité, traditions et beauté naturelle.', 'Ouest', 'CHEFFERIE', 5.5167, 10.4167, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Lac_Baleng2.jpg/960px-Lac_Baleng2.jpg'),
  ('Chefferie de Bameka', 'Petit royaume des Hauts-Plateaux, Bameka perpétue l''art des cases à colonnes sculptées.', 'Ouest', 'CHEFFERIE', 5.3, 10.35, NULL),
  ('Chefferie de Batié', 'Aux confins des Hauts-Plateaux, Batié séduit par ses traditions vivaces et ses paysages de montagne.', 'Ouest', 'CHEFFERIE', 5.2667, 10.3, NULL),
  ('Chefferie de Bahouan', 'Ce royaume Bamiléké préserve fièrement ses cases ancestrales et ses cérémonies traditionnelles.', 'Ouest', 'CHEFFERIE', 5.35, 10.3, NULL),
  ('Chefferie de Bandja', 'Au cœur du Haut-Nkam, Bandja perpétue l''héritage des forgerons et des sociétés secrètes Bamiléké.', 'Ouest', 'CHEFFERIE', 5.2, 10.2, NULL),
  ('Chefferie de Babadjou', 'À la frontière des Grassfields, Babadjou marie traditions Bamiléké et paysages de hautes terres.', 'Ouest', 'CHEFFERIE', 5.7, 10.15, NULL),
  ('Chefferie de Bansoa', 'Ce royaume de la Menoua déploie ses cases coiffées de chaume au milieu de collines verdoyantes.', 'Ouest', 'CHEFFERIE', 5.4, 10.15, NULL),
  ('Chefferie de Balessing', 'Niché dans la Menoua, Balessing conserve ses rites de masques et son architecture traditionnelle.', 'Ouest', 'CHEFFERIE', 5.4, 10.1, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Balessing_Carrefour.jpg/960px-Balessing_Carrefour.jpg'),
  ('Chefferie de Bafang', 'Capitale animée du Haut-Nkam, Bafang allie patrimoine Bamiléké et carrefour commerçant vivant.', 'Ouest', 'CHEFFERIE', 5.1611, 10.1789, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Chefferie_of_Bafang_-_panoramio.jpg/960px-Chefferie_of_Bafang_-_panoramio.jpg'),
  ('Chefferie de Bamendjinda', 'Au pays des Bamboutos, Bamendjinda perpétue les traditions et les danses masquées des Grassfields.', 'Ouest', 'CHEFFERIE', 5.63, 10.25, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Bamendjinda.jpg/960px-Bamendjinda.jpg'),
  ('Chefferie de Bangang', 'Sur les hauteurs des Bamboutos, Bangang offre cases ancestrales et panoramas à couper le souffle.', 'Ouest', 'CHEFFERIE', 5.55, 10.15, NULL),
  ('Musée des Civilisations de Dschang', 'En bordure du lac, ce musée moderne célèbre la diversité des quatre grandes aires culturelles du Cameroun.', 'Ouest', 'MUSEUM', 5.4469, 10.0539, 'https://commons.wikimedia.org/wiki/Special:FilePath/Musee_des_civilisations,_Dschang,_Cameroon.jpg'),
  ('Lac municipal de Dschang', 'Havre de fraîcheur bordé de jardins, ce lac paisible invite à la promenade au cœur de la cité climatique.', 'Ouest', 'NATURE', 5.445, 10.056, 'https://commons.wikimedia.org/wiki/Special:FilePath/Musée_des_Civilisations_et_le_Lac_Municipal_de_Dschang.jpg'),
  ('Lac Baleng', 'Lac de cratère aux eaux mystérieuses, lieu sacré niché dans la verdure au nord de Bafoussam.', 'Ouest', 'NATURE', 5.55, 10.43, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac_Baleng.jpg'),
  ('Lac Petponoun', 'Miroir d''eau bordé de collines verdoyantes, ce lac de cratère ravit les amoureux de quiétude près de Foumbot.', 'Ouest', 'NATURE', 5.56, 10.7, 'https://commons.wikimedia.org/wiki/Special:FilePath/Petpenoun-Foumbot.jpg'),
  ('Lac Monoun', 'Lac de cratère paisible chargé d''histoire géologique, blotti dans le pays Bamoun près de Foumbot.', 'Ouest', 'NATURE', 5.5797, 10.5897, NULL),
  ('Chutes d''Ekom-Nkam', 'Cascade vertigineuse de 80 mètres jaillissant d''une forêt luxuriante, immortalisée dans le film Greystoke.', 'Ouest', 'NATURE', 5.0667, 9.9667, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ekom_falls.jpg'),
  ('Chutes de la Métché', 'Entre Bafoussam et Bandjoun, ces chutes spectaculaires se déversent dans un écrin de verdure chargé d''histoire.', 'Ouest', 'NATURE', 5.4167, 10.3333, 'https://commons.wikimedia.org/wiki/Special:FilePath/Les_chutes_de_la_metché.jpg'),
  ('Réserve forestière de Santchou', 'Sanctuaire de la plaine des Mbô, cette réserve abrite oiseaux rares et forêts dans un écrin sauvage.', 'Ouest', 'NATURE', 5.25, 9.9667, NULL),
  ('Mont Bamboutos', 'Toit verdoyant de l''Ouest, ce massif volcanique culmine à plus de 2700 m offrant des randonnées grandioses.', 'Ouest', 'NATURE', 5.65, 10.05, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cameroon_line.svg/960px-Cameroon_line.svg.png'),
  ('Mont Mbapit', 'Volcan endormi couronné d''un lac de cratère, le Mbapit récompense les marcheurs d''un panorama saisissant.', 'Ouest', 'NATURE', 5.8, 10.95, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Le_volcan_M%27Bapit.jpg/960px-Le_volcan_M%27Bapit.jpg'),
  ('Ville de Foumbot', 'Cité maraîchère animée du pays Bamoun, Foumbot séduit par ses marchés colorés et ses terres volcaniques fertiles.', 'Ouest', 'CULTURE', 5.5, 10.6333, 'https://commons.wikimedia.org/wiki/Special:FilePath/Ville_de_Foumbot_01.jpg'),
  ('La Nouvelle Liberté', 'Sculpture monumentale en métal recyclé de Joseph-Francis Sumégné, devenue l''emblème vibrant du rond-point Deido à Douala.', 'Littoral', 'HERITAGE', 4.07, 9.705, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Statue_de_la_nouvelle_liberte_Douala.jpg/960px-Statue_de_la_nouvelle_liberte_Douala.jpg'),
  ('Cathédrale Saints-Pierre-et-Paul de Bonadibong', 'Joyau d''architecture religieuse au cœur de Douala, la cathédrale catholique dresse ses flèches au-dessus de la ville portuaire.', 'Littoral', 'RELIGIOUS', 4.0494, 9.7009, NULL),
  ('Doual''art', 'Centre d''art contemporain pionnier de Bonanjo, laboratoire des artistes camerounais et veilleur des œuvres urbaines de Douala.', 'Littoral', 'CULTURE', 4.0476, 9.6932, NULL),
  ('Festival Ngondo', 'Grand rendez-vous sacré des peuples Sawa sur les rives du Wouri, où la pirogue mystique plonge vers les esprits de l''eau.', 'Littoral', 'CULTURE', 4.05, 9.685, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/GedNgondoMessager.JPG/960px-GedNgondoMessager.JPG'),
  ('La Pagode (Palais des rois Bell)', 'Élégant palais aux allures asiatiques bâti pour le roi Manga Bell, témoin de l''histoire royale Douala à Bonanjo.', 'Littoral', 'CHEFFERIE', 4.0436, 9.6869, NULL),
  ('Quartier colonial de Bonanjo', 'Promenade dans le Douala d''antan, entre bâtiments allemands centenaires, palais de justice et avenues ombragées.', 'Littoral', 'HERITAGE', 4.045, 9.688, NULL),
  ('Marché Sandaga', 'Cœur battant et coloré du commerce doualais, où pagnes, épices et étoffes composent un tourbillon de vie.', 'Littoral', 'CULTURE', 4.05, 9.7, NULL),
  ('Lac Ossa', 'Paisible miroir d''eau près d''Édéa, refuge des derniers lamantins d''Afrique au milieu d''une nature luxuriante.', 'Littoral', 'NATURE', 3.8, 9.9, NULL),
  ('Réserve de faune de Douala-Édéa', 'Mosaïque de mangroves, forêts et plages atlantiques où tortues marines et oiseaux trouvent un sanctuaire sauvage.', 'Littoral', 'NATURE', 3.5, 9.85, NULL),
  ('Île de Manoka', 'Échappée insulaire dans l''estuaire du Wouri, entre villages de pêcheurs, mangroves et horizons d''océan.', 'Littoral', 'NATURE', 3.95, 9.65, NULL),
  ('Yabassi', 'Petite ville pittoresque perchée au-dessus du fleuve Nkam, point de départ idéal pour la randonnée et la nature.', 'Littoral', 'CULTURE', 4.45, 9.9667, 'https://upload.wikimedia.org/wikipedia/commons/3/30/%C3%89glise_catholique_de_Yabassi.jpg'),
  ('Nkongsamba', 'Ancienne cité ferroviaire au pied du Manengouba, étape verdoyante entre plantations et reliefs du Moungo.', 'Littoral', 'CULTURE', 4.9547, 9.9404, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nkongsamba_01.jpg/960px-Nkongsamba_01.jpg'),
  ('Pont sur le Wouri', 'Long ruban d''acier enjambant le fleuve Wouri, porte d''entrée mythique et carte postale de Douala.', 'Littoral', 'HERITAGE', 4.0556, 9.6889, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Pont_Wouri_1.jpg/960px-Pont_Wouri_1.jpg'),
  ('Monument de la Réunification', 'Spirale de béton signée Engelbert Mveng célébrant l''union des deux Cameroun, symbole majeur de Yaoundé.', 'Centre', 'HERITAGE', 3.8689, 11.5219, 'https://commons.wikimedia.org/wiki/Special:FilePath/Monument_Reunification_4.JPG'),
  ('Musée National du Cameroun', 'Ancien palais présidentiel devenu écrin des trésors des dix régions, du Grassfields au Sahel.', 'Centre', 'MUSEUM', 3.8665, 11.518, 'https://commons.wikimedia.org/wiki/Special:FilePath/Mus%C3%A9e_National_du_Cameroun_01.JPG'),
  ('Cathédrale Notre-Dame des Victoires', 'Cathédrale métropolitaine de Yaoundé aux fresques colorées, havre de recueillement au centre de la capitale.', 'Centre', 'RELIGIOUS', 3.8666, 11.5191, 'https://commons.wikimedia.org/wiki/Special:FilePath/Yaound%C3%A9_Cath%C3%A9drale.jpg'),
  ('Basilique Marie-Reine-des-Apôtres de Mvolyé', 'Majestueuse basilique dressée sur la colline de Mvolyé, berceau spirituel du catholicisme camerounais.', 'Centre', 'RELIGIOUS', 3.8598, 11.5179, NULL),
  ('Musée d''Art Camerounais du Mont-Fébé', 'Niché dans le monastère bénédictin du Mont-Fébé, il abrite masques, bronzes et trésors d''art traditionnel.', 'Centre', 'MUSEUM', 3.9, 11.51, NULL),
  ('Jardin Zoologique de Mvog-Betsi', 'Sanctuaire animalier au cœur de Yaoundé, où gorilles, panthères et primates sauvés trouvent refuge.', 'Centre', 'NATURE', 3.85, 11.49, NULL),
  ('Parc National de la Mefou', 'Forêt sanctuaire aux portes de Yaoundé, foyer protégé des gorilles et chimpanzés orphelins du Cameroun.', 'Centre', 'NATURE', 3.6167, 11.5667, NULL),
  ('Chutes de la Nachtigal', 'Cascades tumultueuses de la Sanaga au nord-est de Yaoundé, spectacle d''eau et de roches en pleine nature.', 'Centre', 'NATURE', 4.35, 11.6333, NULL),
  ('Site écotouristique d''Ebogo', 'Forêt galerie le long du Nyong près de Mbalmayo, paradis de pirogue, d''arbres géants et d''oiseaux.', 'Centre', 'NATURE', 3.4, 11.4667, NULL),
  ('Palais des Congrès de Yaoundé', 'Imposant édifice surplombant la capitale, écrin des grands rendez-vous nationaux et belvédère sur les sept collines.', 'Centre', 'HERITAGE', 3.881, 11.521, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg/960px-Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg'),
  ('Mont Fébé', 'Colline boisée dominant Yaoundé, offrant panoramas, golf et fraîcheur au-dessus de la ville aux sept collines.', 'Centre', 'NATURE', 3.905, 11.507, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/V%C3%A9g%C3%A9tation_sur_le_Mont_F%C3%A9b%C3%A9.jpg/960px-V%C3%A9g%C3%A9tation_sur_le_Mont_F%C3%A9b%C3%A9.jpg'),
  ('Lac municipal de Yaoundé', 'Plan d''eau paisible au centre de la capitale, lieu de promenade et de détente prisé des Yaoundéens.', 'Centre', 'NATURE', 3.865, 11.513, NULL),
  ('Marché Mokolo', 'Labyrinthe grouillant et coloré, le plus grand marché populaire de Yaoundé, immersion totale dans la vie locale.', 'Centre', 'CULTURE', 3.88, 11.505, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/March%C3%A9_Mokolo_%C3%A0_Yaound%C3%A9.jpg/960px-March%C3%A9_Mokolo_%C3%A0_Yaound%C3%A9.jpg'),
  ('Musée de la Blackitude', 'Collection privée passionnante d''art Bamiléké et Grassfields, trésor caché du patrimoine au centre de Yaoundé.', 'Centre', 'MUSEUM', 3.869, 11.515, NULL),
  ('Centre Artisanal de Yaoundé', 'Vitrine vivante du savoir-faire camerounais, où sculptures, perles et tissages racontent toutes les régions.', 'Centre', 'CULTURE', 3.864, 11.516, NULL),
  ('Boulevard du 20 Mai', 'Grande esplanade de la fête nationale à Yaoundé, théâtre des défilés et cœur cérémoniel du pays.', 'Centre', 'HERITAGE', 3.8667, 11.5167, NULL),
  ('Mausolée de Charles Atangana', 'Sépulture du célèbre chef supérieur Ewondo-Béti à Mvolyé, mémoire d''une grande figure de l''histoire camerounaise.', 'Centre', 'HERITAGE', 3.843, 11.508, NULL),
  ('Mbalmayo', 'Ville-jardin posée sur les rives du Nyong, réputée pour son école des Eaux et Forêts et ses ateliers d''art.', 'Centre', 'CULTURE', 3.5167, 11.5, NULL),
  ('Eseka', 'Carrefour ferroviaire historique du Centre, niché dans les collines verdoyantes le long de la voie Douala-Yaoundé.', 'Centre', 'HERITAGE', 3.65, 10.7667, NULL),
  ('Parc National de Mpem et Djim', 'Vaste étendue sauvage près de Ntui, mosaïque de savanes, forêts et rivières peuplées d''une faune discrète.', 'Centre', 'NATURE', 4.9, 11.5, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cameroon_physical_map.svg/960px-Cameroon_physical_map.svg.png'),
  ('Akonolinga', 'Bourgade riveraine du Nyong, célèbre pour ses paysages fluviaux paisibles et ses traditions du pays Béti.', 'Centre', 'CULTURE', 3.7667, 12.25, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/CAM-Akonolinga-Grande_rue.jpg/960px-CAM-Akonolinga-Grande_rue.jpg'),
  ('Lacs jumeaux et plateau du pays Eton', 'Douces collines et villages traditionnels au nord de Yaoundé, immersion dans la culture Eton du Centre.', 'Centre', 'CULTURE', 4.1667, 11.5333, NULL),
  ('Chutes de la Lobé', 'Spectacle rare au monde, la Lobé se jette directement dans l''océan Atlantique au milieu des plages de sable blanc, à quelques kilomètres de Kribi.', 'Sud', 'NATURE', 2.8667, 9.8833, 'https://commons.wikimedia.org/wiki/Special:FilePath/Chutes_de_la_Lobe.jpg'),
  ('Plages de Kribi', 'Sable fin, cocotiers et eaux turquoise : Kribi est la perle balnéaire du Cameroun, idéale pour savourer poissons grillés face à l''océan.', 'Sud', 'NATURE', 2.935, 9.91, 'https://commons.wikimedia.org/wiki/Special:FilePath/Kribi.jpg'),
  ('Plage de Londji', 'Petit village de pêcheurs au nord de Kribi, Londji séduit par sa plage paisible et le ballet coloré des pirogues au lever du soleil.', 'Sud', 'NATURE', 3.05, 9.93, NULL),
  ('Grand Batanga', 'Authentique village de pêcheurs Batanga au sud de Kribi, célèbre pour son mystérieux Rocher du Loup posé dans les vagues.', 'Sud', 'CULTURE', 2.83, 9.88, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Lonji-8.jpg/960px-Lonji-8.jpg'),
  ('Parc national de Campo-Ma''an', 'Vaste sanctuaire de forêt équatoriale abritant éléphants, gorilles et mandrills, entre l''océan et le fleuve Ntem.', 'Sud', 'NATURE', 2.35, 10.4, 'https://upload.wikimedia.org/wikipedia/commons/7/79/Habituation_des_Gorilles.jpg'),
  ('Site de ponte des tortues d''Ebodjé', 'Sur les plages d''Ebodjé, les tortues marines viennent pondre chaque nuit d''octobre à février, un émerveillement protégé par les villageois.', 'Sud', 'NATURE', 2.58, 9.86, NULL),
  ('Campo', 'Ville frontière posée sur l''estuaire du Ntem, Campo ouvre la porte de la grande forêt et des plages sauvages aux confins de la Guinée équatoriale.', 'Sud', 'NATURE', 2.3667, 9.8167, NULL),
  ('Chutes de Memve''ele', 'Surnommées « les miracles de Dieu », ces cascades grondantes du fleuve Ntem dévalent près de Nyabessang dans un écrin de forêt vierge.', 'Sud', 'NATURE', 2.4, 10.43, NULL),
  ('Ebolowa', 'Capitale du cacao camerounais, Ebolowa charme par ses plantations verdoyantes, son lac municipal et l''hospitalité du pays bulu.', 'Sud', 'CULTURE', 2.917, 11.15, 'https://commons.wikimedia.org/wiki/Special:FilePath/Carrefour_An_2000.jpg'),
  ('Centre touristique de Nkolandom', 'Niché sur les collines près d''Ebolowa, Nkolandom mêle grottes, cascades, randonnées et bains de nature au cœur du pays bulu.', 'Sud', 'NATURE', 2.85, 11.18, NULL),
  ('Sangmélima', 'Cité forestière dynamique du pays boulou, Sangmélima est une étape verte vers le grand sud et ses villages traditionnels.', 'Sud', 'OTHER', 2.933, 11.983, NULL),
  ('Sanctuaire à gorilles de Mengame', 'Aux confins de la frontière gabonaise, ce sanctuaire forestier protège gorilles et chimpanzés dans une nature encore intacte.', 'Sud', 'NATURE', 2.3, 12.4, NULL),
  ('Lolodorf', 'Bourgade pittoresque blottie dans la forêt, Lolodorf est une fenêtre sur la culture des peuples pygmées Bagyeli du sud.', 'Sud', 'CULTURE', 3.23, 10.73, NULL),
  ('Bipindi', 'Au cœur de la forêt entre Kribi et Lolodorf, Bipindi invite à la rencontre des campements pygmées Bagyeli et de leurs savoirs ancestraux.', 'Sud', 'CULTURE', 3.08, 10.42, 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Bipindi_3828587.png'),
  ('Grottes et python sacré d''Akok', 'Lieux légendaires du pays sud, les grottes d''Akok Bekoué et le mythique python d''Akok''okas nourrissent récits et croyances ancestrales.', 'Sud', 'HERITAGE', 2.95, 11.2, NULL),
  ('Ambam', 'Carrefour des trois frontières Cameroun-Gabon-Guinée équatoriale, Ambam vibre du métissage culturel du grand sud forestier.', 'Sud', 'OTHER', 2.383, 11.283, NULL),
  ('Djoum', 'Petite ville forestière du grand sud, Djoum est une porte d''entrée vers les pistes sauvages et les villages des chasseurs-cueilleurs Baka.', 'Sud', 'OTHER', 2.67, 12.67, NULL),
  ('Réserve de faune du Dja', 'Joyau classé au patrimoine mondial de l''UNESCO, cette immense forêt presque intacte abrite gorilles, éléphants et le peuple Baka.', 'Est', 'NATURE', 3, 13, 'https://commons.wikimedia.org/wiki/Special:FilePath/Dja_River_and_pirogue.JPG'),
  ('Parc national de Lobéké', 'Au cœur de la forêt équatoriale du sud-est, Lobéké offre depuis ses miradors le spectacle d''éléphants et de gorilles dans les clairières.', 'Est', 'NATURE', 2.25, 15.75, 'https://commons.wikimedia.org/wiki/Special:FilePath/First_mirador_in_Lob%C3%A9k%C3%A9.jpg'),
  ('Parc national de Boumba-Bek', 'Forêt primaire à la densité d''éléphants exceptionnelle, Boumba-Bek forme avec Nki le plus vaste sanctuaire sauvage du Cameroun.', 'Est', 'NATURE', 2.7, 15.2, NULL),
  ('Parc national de Nki', 'Traversé par les chutes spectaculaires de la Dja, Nki est un sanctuaire reculé de gorilles et d''éléphants au bout de la forêt orientale.', 'Est', 'NATURE', 2.3, 14.5, NULL),
  ('Parc national de Deng Deng', 'Refuge de la population de gorilles la plus septentrionale, Deng Deng déploie ses forêts luxuriantes près du réservoir de Lom Pangar.', 'Est', 'NATURE', 5.18, 13.52, NULL),
  ('Réservoir de Lom Pangar', 'Vaste lac artificiel né du barrage sur la Sanaga, Lom Pangar dessine des paysages d''eau et de forêt inédits à l''est du pays.', 'Est', 'OTHER', 5.45, 13.55, NULL),
  ('Bertoua', 'Capitale de l''Est et porte de la grande forêt, Bertoua mêle marchés animés, artisanat et carrefour des cultures de la région.', 'Est', 'OTHER', 4.583, 13.683, 'https://commons.wikimedia.org/wiki/Special:FilePath/Plaque_Bertoua.jpg'),
  ('Chefferie traditionnelle de Batouri', 'Au pays Kako, la chefferie de Batouri dévoile regalia, autorité coutumière et cérémonies colorées au rythme du grand marché.', 'Est', 'CHEFFERIE', 4.433, 14.367, NULL),
  ('Yokadouma', 'Dernière grande ville avant la forêt profonde, Yokadouma est le point de départ vers les parcs du sud-est et les communautés Baka.', 'Est', 'CULTURE', 3.52, 15.05, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Route_de_Yokadouma.jpg/960px-Route_de_Yokadouma.jpg'),
  ('Abong-Mbang', 'Posée sur le haut Nyong, Abong-Mbang séduit par son fleuve majestueux, son artisanat du bois et son ambiance de cité forestière.', 'Est', 'OTHER', 3.983, 13.183, NULL),
  ('Lomié', 'Porte orientale de la réserve du Dja, Lomié est le rendez-vous des amoureux de forêt et des campements du peuple Baka.', 'Est', 'CULTURE', 3.15, 13.62, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Lomi%C3%A9_crossroads.jpg/960px-Lomi%C3%A9_crossroads.jpg'),
  ('Villages Baka du sud-est', 'Au fil des pistes forestières, les campements du peuple Baka partagent chants polyphoniques, pharmacopée et savoir-faire des chasseurs-cueilleurs.', 'Est', 'CULTURE', 3.2, 14, 'https://upload.wikimedia.org/wikipedia/commons/5/54/Baka_dancers_June_2006.jpg'),
  ('Garoua-Boulaï', 'Ville-frontière vibrante aux portes de la Centrafrique, Garoua-Boulaï est un carrefour de routes, de peuples et de commerce de l''Est.', 'Est', 'OTHER', 5.88, 14.55, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Mosqu%C3%A9e_%2828604170443%29.jpg/960px-Mosqu%C3%A9e_%2828604170443%29.jpg'),
  ('Bétaré-Oya', 'Cité aurifère légendaire, Bétaré-Oya raconte l''épopée des chercheurs d''or au milieu des collines et des rivières de l''Est.', 'Est', 'OTHER', 5.6, 14.08, NULL),
  ('Poste colonial allemand de Doumé', 'Vestige de l''époque coloniale allemande, l''ancien poste fortifié de Doumé domine le paysage et témoigne d''un passé chargé d''histoire.', 'Est', 'HERITAGE', 4.23, 13.45, NULL),
  ('Forêt communale de Dimako', 'Modèle pionnier de gestion forestière communautaire, Dimako invite à découvrir la forêt de l''Est sur ses sentiers d''écotourisme.', 'Est', 'NATURE', 4.38, 13.55, NULL),
  ('Marché central de Batouri', 'Étals débordant de plantains, poissons fumés, épices et pagnes, le marché de Batouri est un carnaval de couleurs et de saveurs de l''Est.', 'Est', 'CULTURE', 4.4335, 14.3675, NULL),
  ('Somalomo', 'Village d''accès nord à la réserve du Dja, Somalomo ouvre les sentiers vers la forêt classée et ses guides Baka et Badjoué.', 'Est', 'CULTURE', 3.38, 12.73, NULL),
  ('Palais du Lamido de Ngaoundéré', 'Joyau de l''architecture peule, ce palais aux cases sacrées et aux toits de chaume vous plonge dans la cour vivante d''un royaume séculaire.', 'Adamaoua', 'CHEFFERIE', 7.327, 13.584, 'https://commons.wikimedia.org/wiki/Special:FilePath/King''s_palace_Ngaoundere.PNG'),
  ('Grande Mosquée du Lamido de Ngaoundéré', 'Dressée au cœur de la cité, sa silhouette élégante résume des siècles de ferveur et de raffinement islamique sur le plateau de l''Adamaoua.', 'Adamaoua', 'RELIGIOUS', 7.323, 13.584, 'https://commons.wikimedia.org/wiki/Special:FilePath/LamidoGrandMosque.jpg'),
  ('Lac Tison', 'Niché dans un ancien cratère et bordé d''arbres, ce lac aux eaux paisibles est l''escapade nature favorite des Ngaoundéréens.', 'Adamaoua', 'NATURE', 7.25, 13.6, 'https://commons.wikimedia.org/wiki/Special:FilePath/Le_lac_de_cratère_de_Tizon_à_Ngaoundéré.jpg'),
  ('Lac de Mbalang', 'Miroir bleu posé dans un cratère volcanique, ce lac aux abords verdoyants invite à la baignade et à la rêverie loin de l''agitation.', 'Adamaoua', 'NATURE', 7.3, 13.73, NULL),
  ('Chutes de la Vina', 'Sur la rivière Vina, l''eau dévale les roches du plateau dans un fracas rafraîchissant, écrin sauvage aux portes de Ngaoundéré.', 'Adamaoua', 'NATURE', 7.1, 13.52, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Madera_County_California_Incorporated_and_Unincorporated_areas_La_Vina_Highlighted_0640872.svg/960px-Madera_County_California_Incorporated_and_Unincorporated_areas_La_Vina_Highlighted_0640872.svg.png'),
  ('Chutes de Tello', 'Cascade spectaculaire jaillissant des hauteurs de l''Adamaoua, un rideau d''écume qui récompense les amateurs de randonnée.', 'Adamaoua', 'NATURE', 7.5, 13.5, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Chute_de_Tello_18.jpg/960px-Chute_de_Tello_18.jpg'),
  ('Chutes de Lancrenon', 'Parmi les plus majestueuses du pays, ces chutes vertigineuses plongent dans une gorge luxuriante près de la frontière orientale.', 'Adamaoua', 'NATURE', 7.1, 14.85, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Chutes_de_Lancrenon_%C3%A0_Yamba1.jpg/960px-Chutes_de_Lancrenon_%C3%A0_Yamba1.jpg'),
  ('Parc national du Mbam et Djerem', 'Vaste mosaïque de savanes et de forêts traversée de rivières, sanctuaire d''éléphants et de chimpanzés à la lisière de l''Adamaoua.', 'Adamaoua', 'NATURE', 5.75, 12.75, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cameroon_physical_map.svg/960px-Cameroon_physical_map.svg.png'),
  ('Lac et barrage de Mbakaou', 'Immense retenue d''eau aux reflets argentés près de Tibati, paradis des pêcheurs et des oiseaux migrateurs.', 'Adamaoua', 'NATURE', 6.33, 12.82, NULL),
  ('Ranch de Ngaoundaba', 'Entre lac de cratère et collines boisées, ce domaine paisible offre l''une des plus belles échappées vertes de l''Adamaoua.', 'Adamaoua', 'NATURE', 7.12, 13.73, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Le_lac_de_N%27Gaoundaba_pr%C3%A8s_de_Ngaound%C3%A9r%C3%A9.jpg/960px-Le_lac_de_N%27Gaoundaba_pr%C3%A8s_de_Ngaound%C3%A9r%C3%A9.jpg'),
  ('Palais du Lamido de Tibati', 'Témoin du puissant lamidat de Tibati, ce palais traditionnel garde la mémoire des cavaliers et des fêtes du Mbam.', 'Adamaoua', 'CHEFFERIE', 6.47, 12.63, NULL),
  ('Palais du Lamido de Banyo', 'Perché sur les hauts plateaux verdoyants, le palais de Banyo perpétue les fastes et les rites d''un vieux royaume peul.', 'Adamaoua', 'CHEFFERIE', 6.75, 11.82, NULL),
  ('Parc national de la Bénoué', 'Le long du fleuve Bénoué, hippopotames, antilopes et lions évoluent dans une savane dorée classée réserve de biosphère.', 'Nord', 'NATURE', 8.4, 13.83, 'https://commons.wikimedia.org/wiki/Special:FilePath/Benoue_National_park_hippo.jpg'),
  ('Parc national de Bouba Ndjida', 'Joyau sauvage du Grand Nord, ce parc abrite éléphants, élands de Derby et babouins dans des paysages de brousse intacte.', 'Nord', 'NATURE', 8.67, 14.5, 'https://commons.wikimedia.org/wiki/Special:FilePath/Babouin_olive_(Papio_anubis)_au_Parc_National_de_Bouba_Ndjidda,_Cameroun.jpg'),
  ('Parc national du Faro', 'Aux confins de la frontière nigériane, ce sanctuaire reculé déroule des plaines giboyeuses où rôdent rhinocéros d''antan et grands fauves.', 'Nord', 'NATURE', 8.3, 12.75, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cameroon_physical_map.svg/960px-Cameroon_physical_map.svg.png'),
  ('Grand marché de Garoua', 'Carrefour bouillonnant du Nord, ses étals colorés mêlent cotonnades, épices et artisanat au rythme du fleuve Bénoué.', 'Nord', 'CULTURE', 9.3, 13.39, 'https://commons.wikimedia.org/wiki/Special:FilePath/Marche_Garoua_Nord_Cameroon.jpg'),
  ('Lac et barrage de Lagdo', 'Vaste mer intérieure née du fleuve Bénoué, ses rives offrent couchers de soleil flamboyants et poissons à profusion.', 'Nord', 'NATURE', 9.05, 13.73, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Lagdo_Dam.jpg/960px-Lagdo_Dam.jpg'),
  ('Palais du Lamido de Garoua', 'Résidence du chef traditionnel du Nord, ce palais incarne l''autorité et l''art de vivre peul sur les bords de la Bénoué.', 'Nord', 'CHEFFERIE', 9.3, 13.39, NULL),
  ('Lamidat de Rey Bouba', 'Cité-palais fortifiée et mystérieuse, Rey Bouba demeure l''un des plus puissants et secrets royaumes traditionnels du Cameroun.', 'Nord', 'CHEFFERIE', 8.67, 14.18, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Lamidat_de_Rey-Bouba_en_janvier_1974.jpg/960px-Lamidat_de_Rey-Bouba_en_janvier_1974.jpg'),
  ('Hosséré Vokré', 'Toit du Nord, ce massif granitique aux pentes abruptes domine la région de Poli et défie les randonneurs.', 'Nord', 'NATURE', 8.33, 12.87, NULL),
  ('Grande mosquée de Garoua', 'Repère spirituel de la capitale du Nord, ses minarets veillent sur une ville façonnée par l''islam et le négoce fluvial.', 'Nord', 'RELIGIOUS', 9.3, 13.4, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg/960px-Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg'),
  ('Lamidat de Bibémi', 'Vieux royaume peul aux portes de Garoua, Bibémi conserve son palais de terre et ses traditions équestres.', 'Nord', 'CHEFFERIE', 9.31, 13.88, NULL),
  ('Parc national de Waza', 'Le plus célèbre safari du Cameroun, où éléphants, girafes et lions se rassemblent dans une savane d''acacias à perte de vue.', 'Extreme-Nord', 'NATURE', 11.32, 14.65, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bain_des_éléphants,_parc_de_Waza,_Nord_Cameroun_(25963018142).jpg'),
  ('Rhumsiki et le Pic de Kapsiki', 'Cathédrale de roche surgie d''un paysage quasi lunaire, Rhumsiki est le panorama le plus envoûtant des monts Mandara.', 'Extreme-Nord', 'NATURE', 10.53, 13.62, 'https://commons.wikimedia.org/wiki/Special:FilePath/Rhumsiki_peak,_North_Cameroon_(25989204581).jpg'),
  ('Monts Mandara', 'Chaîne volcanique aux pics déchiquetés et aux villages perchés en terrasses, royaume des montagnards Kapsiki et Mafa.', 'Extreme-Nord', 'NATURE', 10.7, 13.7, NULL),
  ('Village d''Oudjila', 'Accroché aux monts Mandara, ce village Podokwo séduit par ses cases en terre, sa chefferie et ses panoramas saisissants.', 'Extreme-Nord', 'CULTURE', 11.08, 14.17, NULL),
  ('Cases obus de Pouss', 'Sculptées en obus de terre par le peuple Mousgoum, ces demeures coniques sont un chef-d''œuvre d''architecture vernaculaire africaine.', 'Extreme-Nord', 'CULTURE', 10.85, 15.05, 'https://commons.wikimedia.org/wiki/Special:FilePath/Cam0505_Habitation_de_Pouss_Case_obus.jpg'),
  ('Lac de Maga', 'Grand lac artificiel bordé de rizières et de pirogues, refuge d''innombrables oiseaux d''eau à l''extrême nord du pays.', 'Extreme-Nord', 'NATURE', 10.84, 14.95, 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac_de_Maga_dans_l''extrême_nord1.jpg'),
  ('Parc national de Kalamaloué', 'Petit parc giboyeux près de Kousséri, où éléphants et antilopes s''abreuvent aux bras du fleuve Chari.', 'Extreme-Nord', 'NATURE', 12.05, 14.93, NULL),
  ('Parc national de Mozogo-Gokoro', 'Îlot de forêt dense préservée au pied des monts Mandara, sanctuaire rare de biodiversité dans le Sahel.', 'Extreme-Nord', 'NATURE', 11.02, 13.95, NULL),
  ('Palais du Lamido de Maroua', 'Au cœur de la capitale du Diamaré, le palais résonne des tambours et des danses traditionnelles données en l''honneur du Lamido.', 'Extreme-Nord', 'CHEFFERIE', 10.59, 14.31, 'https://commons.wikimedia.org/wiki/Special:FilePath/Danse_traditionnelle_chez_le_Lamido_de_Maroua.jpg'),
  ('Musée du Diamaré', 'À Maroua, ce musée raconte les peuples du Grand Nord à travers masques, parures et objets du quotidien sahélien.', 'Extreme-Nord', 'MUSEUM', 10.59, 14.32, NULL),
  ('Grand marché de Maroua', 'Temple de l''artisanat sahélien, on y déniche maroquinerie, bijoux et tissages dans un tourbillon de couleurs et de senteurs.', 'Extreme-Nord', 'CULTURE', 10.59, 14.32, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/VUE_DE_MAROUA_DU_MONT_MAYO_IB%C3%89_%28EXTR%C3%8AME-NORD_CAMEROUN%29.jpg/960px-VUE_DE_MAROUA_DU_MONT_MAYO_IB%C3%89_%28EXTR%C3%8AME-NORD_CAMEROUN%29.jpg'),
  ('Dent de Mindif', 'Aiguille rocheuse dressée seule dans la plaine, ce pic spectaculaire attire grimpeurs et photographes près de Maroua.', 'Extreme-Nord', 'NATURE', 10.4, 14.45, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Pic_Mindif3.jpg/960px-Pic_Mindif3.jpg'),
  ('Mokolo', 'Porte d''entrée des monts Mandara, cette cité animée vit au rythme des marchés montagnards et des fêtes Mafa.', 'Extreme-Nord', 'CULTURE', 10.74, 13.8, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Zbi%C3%B3r_prosa_z_pola_-_Mokolo_-_001954s.jpg/960px-Zbi%C3%B3r_prosa_z_pola_-_Mokolo_-_001954s.jpg'),
  ('Marché de Mora', 'Célèbre marché hebdomadaire au pied des Mandara, point de rencontre haut en couleur des peuples Wandala et montagnards.', 'Extreme-Nord', 'CULTURE', 11.05, 14.14, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Hotel_de_ville_de_Mora.jpg/960px-Hotel_de_ville_de_Mora.jpg'),
  ('Sultanat de Logone-Birni', 'Labyrinthe de murs de terre ocre, le palais des sultans Kotoko est un éblouissant témoignage d''architecture sahélienne.', 'Extreme-Nord', 'HERITAGE', 11.78, 15.08, NULL),
  ('Rive camerounaise du lac Tchad', 'Aux confins du pays, les eaux changeantes du lac Tchad nourrissent pêcheurs et oiseaux dans un paysage d''îles et de roseaux.', 'Extreme-Nord', 'NATURE', 12.55, 14.45, NULL),
  ('Village de cases de Yagoua', 'Terre du peuple Toupouri, Yagoua déploie ses cases de terre et ses fêtes de récolte au bord du Logone.', 'Extreme-Nord', 'CULTURE', 10.34, 15.23, 'https://commons.wikimedia.org/wiki/Special:FilePath/Village_de_Cases_Yagoua.jpg'),
  ('Tourou', 'Village des monts Mandara célèbre pour ses femmes coiffées de calebasses colorées, image emblématique du Grand Nord.', 'Extreme-Nord', 'CULTURE', 10.87, 13.63, NULL),
  ('Sultanat de Makari', 'Ancienne cité Kotoko proche du lac Tchad, Makari garde son palais et ses traditions de cavaliers du Sahel.', 'Extreme-Nord', 'CHEFFERIE', 12.58, 14.46, NULL),
  ('Grande mosquée de Maroua', 'Cœur spirituel de la cité sahélienne, ses minarets élancés veillent sur les ruelles ombragées de manguiers.', 'Extreme-Nord', 'RELIGIOUS', 10.59, 14.32, NULL),
  ('Kousséri', 'Ville-frontière posée sur le fleuve Chari face à N''Djamena, carrefour vivant des cultures du bassin du lac Tchad.', 'Extreme-Nord', 'CULTURE', 12.08, 15.03, NULL),
  ('Palais Royal des Rois Bamoun (Foumban)', 'Joyau de six siècles d''histoire, le palais des sultans Bamoun veille fièrement sur Foumban et son trône de perles.', 'Ouest', 'CHEFFERIE', 5.733, 10.9012, 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamun_sultan_palace.jpg'),
  ('Musée des Rois Bamoun (Foumban)', 'Plus de dix mille tresors royaux racontent l''epopee du royaume Bamoun dans un ecrin architectural spectaculaire.', 'Ouest', 'MUSEUM', 5.7285, 10.9005, NULL),
  ('Village des Artisans de Foumban', 'Bronziers, brodeurs et sculpteurs perpetuent le genie createur Bamoun le long de la celebre rue des artisans.', 'Ouest', 'CULTURE', 5.724, 10.895, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Festival Nguon (Foumban)', 'Tous les deux ans, le Nguon ressuscite des rites vieux de 600 ans ou le peuple juge meme son sultan.', 'Ouest', 'CULTURE', 5.729, 10.9, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Grande Mosquee de Foumban', 'Ses minarets elances dominent la cite Bamoun, coeur spirituel d''une ville musulmane a 80 pour cent.', 'Ouest', 'RELIGIOUS', 5.7268, 10.8985, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Chefferie Bandjoun', 'Cases a toits coniques et facades sculptees: la chefferie Bandjoun incarne toute la splendeur de l''art Bamileke.', 'Ouest', 'CHEFFERIE', 5.3667, 10.4167, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/La_r%C3%A9sidence_%28Renov%C3%A9e%29_de_l%27ancien_roi_Nie_KAMGA_Joseph_avant_dernier_chef_Bandjoun.JPG/960px-La_r%C3%A9sidence_%28Renov%C3%A9e%29_de_l%27ancien_roi_Nie_KAMGA_Joseph_avant_dernier_chef_Bandjoun.JPG'),
  ('Bandjoun Station (Musee d''art de Barthelemy Toguo)', 'Un centre d''art contemporain visionnaire ou la creation africaine dialogue avec le monde, signe Barthelemy Toguo.', 'Ouest', 'MUSEUM', 5.4, 10.42, NULL),
  ('Musee des Civilisations (Dschang)', 'Un voyage saisissant a travers les peuples du Cameroun, des Sawa aux Sahaliens, au coeur des montagnes de l''Ouest.', 'Ouest', 'MUSEUM', 5.447, 10.054, NULL),
  ('Festival Medumba (Bangangte)', 'Le pays Medumba celebre ses ancetres, sa langue et sa medecine traditionnelle dans une explosion de couleurs.', 'Ouest', 'CULTURE', 5.15, 10.52, NULL),
  ('Chefferie Bana', 'Perchee sur les hauteurs, la chefferie Bana garde ses totems et ses cases royales aux portes finement sculptees.', 'Ouest', 'CHEFFERIE', 5.13, 10.3, NULL),
  ('Chefferie de Bafut', 'Sanctuaire Achum et foret sacree: la chefferie Bafut, joyau classe, fait revivre la cour vivante du Fon.', 'Nord-Ouest', 'CHEFFERIE', 6.1, 10.1, NULL),
  ('Musee de Babungo (Ndop)', 'Dans l''ancien grand centre de forge du Cameroun, un musee communautaire devoile masques, bronzes et savoir-faire ancestraux.', 'Nord-Ouest', 'MUSEUM', 6.0715, 10.4423, NULL),
  ('Palais des Fons de Nso (Kumbo)', 'Au coeur des Grassfields, le palais du Fon de Nso veille sur l''un des plus puissants royaumes du Nord-Ouest.', 'Nord-Ouest', 'CHEFFERIE', 6.205, 10.67, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Tobin_View_of_the_Cathedral.JPG/960px-Tobin_View_of_the_Cathedral.JPG'),
  ('Festival Ngonnso (Kumbo)', 'Le peuple Nso honore sa reine fondatrice Ngonnso dans un festival vibrant de tambours, danses et fierte ancestrale.', 'Nord-Ouest', 'CULTURE', 6.2, 10.67, NULL),
  ('Cathedrale metropolitaine Saint-Joseph de Bamenda', 'Dressee sur les collines de Bamenda, la cathedrale Saint-Joseph veille sur la capitale des Grassfields.', 'Nord-Ouest', 'RELIGIOUS', 5.96, 10.15, NULL),
  ('Festival Ngondo (Douala)', 'Chaque decembre, les peuples Sawa rendent hommage au fleuve Wouri lors d''une plongee mystique au pays des eaux.', 'Littoral', 'CULTURE', 4.0469, 9.69, NULL),
  ('La Nouvelle Liberte (Douala)', 'Geant de douze metres ne de la ferraille recyclee, ce chef-d''oeuvre de Sumegne incarne l''energie creative de Douala.', 'Littoral', 'HERITAGE', 4.0593, 9.7344, 'https://commons.wikimedia.org/wiki/Special:FilePath/Statue_de_la_nouvelle_liberte_Douala.jpg'),
  ('Cathedrale Saints-Pierre-et-Paul de Douala', 'Edifice emblematique du Littoral, la cathedrale de Douala marie ferveur catholique et memoire coloniale.', 'Littoral', 'RELIGIOUS', 4.049, 9.696, NULL),
  ('La Pagode - Palais des Rois Bell (Douala)', 'Curiosite architecturale aux airs d''Asie, l''ancien palais du roi Manga Bell raconte l''histoire des cotes Douala.', 'Littoral', 'HERITAGE', 4.048, 9.692, NULL),
  ('Espace doual''art', 'Pionnier de l''art contemporain africain, doual''art transforme la ville en galerie a ciel ouvert.', 'Littoral', 'CULTURE', 4.05, 9.695, NULL),
  ('Festival Mpo''o (Edea)', 'Le peuple Bassa celebre ses origines et son identite lors du Mpo''o, grand rendez-vous culturel d''Edea.', 'Littoral', 'CULTURE', 3.8, 10.133, NULL),
  ('Monument de la Reunification (Yaounde)', 'Spirale audacieuse de Mveng et Mpando, ce monument celebre l''union des deux Cameroun en un seul peuple.', 'Centre', 'HERITAGE', 3.8525, 11.5134, NULL),
  ('Basilique Marie-Reine-des-Apotres de Mvolye (Yaounde)', 'Sur la colline de Mvolye, l''une des plus grandes basiliques d''Afrique accueille des milliers de pelerins.', 'Centre', 'RELIGIOUS', 3.8425, 11.5078, 'https://commons.wikimedia.org/wiki/Special:FilePath/Int%C3%A9rieur_Basilique_Marie-Reine_des_ap%C3%B4tres_de_Mvoly%C3%A9_2.jpg'),
  ('Musee National du Cameroun (Yaounde)', 'Dans l''ancien palais presidentiel, le Musee National deroule l''histoire et les arts de tout le pays.', 'Centre', 'MUSEUM', 3.858, 11.517, NULL),
  ('Cathedrale Notre-Dame-des-Victoires (Yaounde)', 'Cathedrale historique de la capitale, Notre-Dame-des-Victoires domine le centre-ville de ses tours elancees.', 'Centre', 'RELIGIOUS', 3.866, 11.518, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Cath%C3%A9drale_Notre-Dame_Yaound%C3%A9.jpg/960px-Cath%C3%A9drale_Notre-Dame_Yaound%C3%A9.jpg'),
  ('Musee d''Art Camerounais (Mont Febe, Yaounde)', 'Niche sur le mont Febe, ce musee benedictin abrite une exceptionnelle collection de masques et bronzes.', 'Centre', 'MUSEUM', 3.905, 11.495, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/B%C3%A2timent_du_mus%C3%A9e_des_B%C3%A9n%C3%A9dictins.jpg/960px-B%C3%A2timent_du_mus%C3%A9e_des_B%C3%A9n%C3%A9dictins.jpg'),
  ('Ngog Lituba (rocher sacre Bassa)', 'Berceau mythique des peuples Bassa, Mpoo et Bati, ce rocher perce est un lieu de memoire et de pelerinage.', 'Centre', 'HERITAGE', 3.92, 10.85, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Coucher_de_soleil_%C3%A0_Tayap.JPG/960px-Coucher_de_soleil_%C3%A0_Tayap.JPG'),
  ('Ancien Palais du Gouverneur allemand (Buea)', 'Au pied du mont Cameroun, l''ancienne residence du gouverneur allemand temoigne du passe colonial de Buea.', 'Sud-Ouest', 'HERITAGE', 4.155, 9.24, 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Silicon_Mountain_as_seen_in_Buea%2C_Cameroon_on_26-06-2019.jpg'),
  ('Memorial du port negrier de Bimbia', 'Site national de memoire, Bimbia conserve la bouleversante Porte du non-retour de la traite negriere.', 'Sud-Ouest', 'HERITAGE', 3.9833, 9.305, NULL),
  ('Mount Cameroon Race of Hope (Buea)', 'Course mythique vers le toit de l''Afrique de l''Ouest, la Race of Hope defie chaque annee le mont Cameroun.', 'Sud-Ouest', 'CULTURE', 4.16, 9.23, NULL),
  ('Palais du Lamido de Ngaoundere', 'Joyau de l''Adamaoua, le palais du Lamido de Ngaoundere accueille le visiteur au son des tambours royaux.', 'Adamaoua', 'CHEFFERIE', 7.327, 13.584, NULL),
  ('Festival Nyem-Nyem (Galim)', 'Au pied du mont Djim, le peuple Nyem-Nyem commemore sa resistance heroique a l''occupant lors d''un festival fervent.', 'Adamaoua', 'CULTURE', 7.13, 12.5, NULL),
  ('Musee du Diamare (Maroua)', 'Fonde en 1955, le musee du Diamare reunit l''art et l''ethnographie des peuples de l''Extreme-Nord.', 'Extreme-Nord', 'MUSEUM', 10.595, 14.315, NULL),
  ('Grande Mosquee de Maroua', 'Au coeur de la cite sahelienne, la grande mosquee de Maroua rythme la vie spirituelle de la capitale du Diamare.', 'Extreme-Nord', 'RELIGIOUS', 10.591, 14.32, NULL),
  ('Cathedrale Sainte-Anne-et-Saint-Joachim d''Ebolowa', 'Edifice majeur du Sud, la cathedrale d''Ebolowa rassemble les fideles au coeur du pays Bulu.', 'Sud', 'RELIGIOUS', 2.915, 11.154, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Cath%C3%A9drale_d%27Abang.jpg/960px-Cath%C3%A9drale_d%27Abang.jpg'),
  ('Villages Baka de Lomie', 'A la lisiere de la grande foret, les communautes Baka partagent chants polyphoniques, danses et savoirs de la jungle.', 'Est', 'CULTURE', 3.15, 13.62, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Lomi%C3%A9_crossroads.jpg/960px-Lomi%C3%A9_crossroads.jpg'),
  ('Cathedrale du Sacre-Coeur de Bertoua', 'Principal sanctuaire de l''Est forestier, la cathedrale de Bertoua veille sur la capitale regionale.', 'Est', 'RELIGIOUS', 4.577, 13.684, NULL),
  ('id', 'name', 'description', 'region', NULL, NULL, 'longitude')
)
INSERT INTO tourism_places
  (id, name, description, region, category, latitude, longitude, image_url, source, source_ref,
   verified, verified_by_account_id, submitted_by_account_id, visibility_scope, created_at, updated_at)
SELECT
  uuid_generate_v4(), d.name, d.description, d.region,
  d.category::"tourism_category", d.lat, d.lng, d.image_url, 'COMMUNITY'::"tourism_source",
  'Recherché sur des sources publiques (Wikipedia, Wikimedia Commons)',
  TRUE, (SELECT id FROM admin), (SELECT id FROM admin), 'PUBLIC'::"visibility_scope", NOW(), NOW()
FROM data d
WHERE NOT EXISTS (SELECT 1 FROM tourism_places t WHERE lower(t.name) = lower(d.name));

-- Backfill photos for places already inserted by an earlier run of this seed.
UPDATE tourism_places t SET image_url = d.image_url
FROM (VALUES
  ('Mont Cameroun', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Cameroon_view_from_Buea_(Soppo).jpg'),
  ('Parc national de Korup', 'https://commons.wikimedia.org/wiki/Special:FilePath/Korup_National_park.jpg'),
  ('Jardin botanique de Limbe', 'https://commons.wikimedia.org/wiki/Special:FilePath/Garden_Information_Center_-_Limbe_Botanic_Garden.jpg'),
  ('Centre de la faune de Limbe', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Limbe_Wildlife_Centre_exterior.JPG/960px-Limbe_Wildlife_Centre_exterior.JPG'),
  ('Down Beach de Limbe', 'https://commons.wikimedia.org/wiki/Special:FilePath/DOWN_BEACH_LIMBE_CAMEROON.jpg'),
  ('Site historique de Bimbia', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bimbia_Slave_Port.jpg'),
  ('Résidence von Puttkamer de Buea', 'https://commons.wikimedia.org/wiki/Special:FilePath/Schloss_von_Puttkamer.jpg'),
  ('Fontaine Bismarck de Buea', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bismarck_Fountain,_Buea.jpg'),
  ('Mont Etinde', 'https://commons.wikimedia.org/wiki/Special:FilePath/View_of_Mt_Etinde.jpg'),
  ('Monument Alfred Saker de Limbe', 'https://commons.wikimedia.org/wiki/Special:FilePath/Alfred_Saker_monument.jpg'),
  ('Mont Kupe', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Statue_of_Kupe%2C_Wellington_Waterfront.jpg/960px-Statue_of_Kupe%2C_Wellington_Waterfront.jpg'),
  ('Palais des Fons de Bafut', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bafut_Palace_-_EcoVillage_-_Cameroon.JPG'),
  ('Musée de Bafut', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mus%C3%A9e_de_Bafut.jpg'),
  ('Palais et Musée de Mankon', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mankon_Palace_(3).JPG'),
  ('Palais du Fon de Nso à Kumbo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Tobin_View_of_the_Cathedral.JPG/960px-Tobin_View_of_the_Cathedral.JPG'),
  ('Musée de Babungo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Sculptures_found_in_the_Babungo_Museum.jpg/960px-Sculptures_found_in_the_Babungo_Museum.jpg'),
  ('Lac Nyos', 'https://commons.wikimedia.org/wiki/Special:FilePath/Nyos_Lake.jpg'),
  ('Lac Oku', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lake_Oku_Cameroon.jpg'),
  ('Chutes de la Menchum', 'https://commons.wikimedia.org/wiki/Special:FilePath/Menchum_Falls_NWprovince_Cameroon.jpg'),
  ('Bamenda et son Up Station', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamenda_from_mountain_road.jpg'),
  ('Commercial Avenue de Bamenda', 'https://commons.wikimedia.org/wiki/Special:FilePath/Commercial_Avenue,_Bamenda,_Cameroon.jpg'),
  ('Cathédrale et mission de Shisong (Kumbo)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Tobin_View_of_the_Cathedral.JPG/960px-Tobin_View_of_the_Cathedral.JPG'),
  ('Palais Royal des Bamoun (Foumban)', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamun_sultan_palace.jpg'),
  ('Musée du Palais des Rois Bamoun', 'https://commons.wikimedia.org/wiki/Special:FilePath/Foumban-Museum1.jpg'),
  ('Festival Nguon de Foumban', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Chefferie de Bandjoun', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bandjoun_palace.jpg'),
  ('Musée de la chefferie de Bandjoun', 'https://commons.wikimedia.org/wiki/Special:FilePath/MUSEE_de_la_chefferie_Bandjoun.jpg'),
  ('Chefferie supérieure de Bafoussam', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bafoussam_chefferie.JPG'),
  ('Chefferie de Batoufam', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chefferie_batoufam.jpg'),
  ('Musée Royal de Batoufam', 'https://commons.wikimedia.org/wiki/Special:FilePath/Entrée_du_musée_Royal_de_Batoufam.jpg'),
  ('Chefferie de Bana', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chefferie_Bana.jpg'),
  ('Chefferie de Bangou', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Carrefour_Bangou.jpg/960px-Carrefour_Bangou.jpg'),
  ('Chefferie de Bangangté', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Bangangte_Marche_A.PNG/960px-Bangangte_Marche_A.PNG'),
  ('Chefferie de Foréké-Dschang', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Pont_du_Plaisir.jpg'),
  ('Chefferie de Balatchi', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Cameroun_from_a_village_balatchi.jpg/960px-Cameroun_from_a_village_balatchi.jpg'),
  ('Chefferie de Baleng', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Lac_Baleng2.jpg/960px-Lac_Baleng2.jpg'),
  ('Chefferie de Balessing', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Balessing_Carrefour.jpg/960px-Balessing_Carrefour.jpg'),
  ('Chefferie de Bafang', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Chefferie_of_Bafang_-_panoramio.jpg/960px-Chefferie_of_Bafang_-_panoramio.jpg'),
  ('Chefferie de Bamendjinda', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Bamendjinda.jpg/960px-Bamendjinda.jpg'),
  ('Musée des Civilisations de Dschang', 'https://commons.wikimedia.org/wiki/Special:FilePath/Musee_des_civilisations,_Dschang,_Cameroon.jpg'),
  ('Lac municipal de Dschang', 'https://commons.wikimedia.org/wiki/Special:FilePath/Musée_des_Civilisations_et_le_Lac_Municipal_de_Dschang.jpg'),
  ('Lac Baleng', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac_Baleng.jpg'),
  ('Lac Petponoun', 'https://commons.wikimedia.org/wiki/Special:FilePath/Petpenoun-Foumbot.jpg'),
  ('Chutes d''Ekom-Nkam', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ekom_falls.jpg'),
  ('Chutes de la Métché', 'https://commons.wikimedia.org/wiki/Special:FilePath/Les_chutes_de_la_metché.jpg'),
  ('Mont Bamboutos', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cameroon_line.svg/960px-Cameroon_line.svg.png'),
  ('Mont Mbapit', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Le_volcan_M%27Bapit.jpg/960px-Le_volcan_M%27Bapit.jpg'),
  ('Ville de Foumbot', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ville_de_Foumbot_01.jpg'),
  ('La Nouvelle Liberté', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Statue_de_la_nouvelle_liberte_Douala.jpg/960px-Statue_de_la_nouvelle_liberte_Douala.jpg'),
  ('Festival Ngondo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/GedNgondoMessager.JPG/960px-GedNgondoMessager.JPG'),
  ('Yabassi', 'https://upload.wikimedia.org/wikipedia/commons/3/30/%C3%89glise_catholique_de_Yabassi.jpg'),
  ('Nkongsamba', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nkongsamba_01.jpg/960px-Nkongsamba_01.jpg'),
  ('Pont sur le Wouri', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Pont_Wouri_1.jpg/960px-Pont_Wouri_1.jpg'),
  ('Monument de la Réunification', 'https://commons.wikimedia.org/wiki/Special:FilePath/Monument_Reunification_4.JPG'),
  ('Musée National du Cameroun', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mus%C3%A9e_National_du_Cameroun_01.JPG'),
  ('Cathédrale Notre-Dame des Victoires', 'https://commons.wikimedia.org/wiki/Special:FilePath/Yaound%C3%A9_Cath%C3%A9drale.jpg'),
  ('Palais des Congrès de Yaoundé', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg/960px-Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg'),
  ('Mont Fébé', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/V%C3%A9g%C3%A9tation_sur_le_Mont_F%C3%A9b%C3%A9.jpg/960px-V%C3%A9g%C3%A9tation_sur_le_Mont_F%C3%A9b%C3%A9.jpg'),
  ('Marché Mokolo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/March%C3%A9_Mokolo_%C3%A0_Yaound%C3%A9.jpg/960px-March%C3%A9_Mokolo_%C3%A0_Yaound%C3%A9.jpg'),
  ('Parc National de Mpem et Djim', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cameroon_physical_map.svg/960px-Cameroon_physical_map.svg.png'),
  ('Akonolinga', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/CAM-Akonolinga-Grande_rue.jpg/960px-CAM-Akonolinga-Grande_rue.jpg'),
  ('Chutes de la Lobé', 'https://commons.wikimedia.org/wiki/Special:FilePath/Chutes_de_la_Lobe.jpg'),
  ('Plages de Kribi', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kribi.jpg'),
  ('Grand Batanga', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Lonji-8.jpg/960px-Lonji-8.jpg'),
  ('Parc national de Campo-Ma''an', 'https://upload.wikimedia.org/wikipedia/commons/7/79/Habituation_des_Gorilles.jpg'),
  ('Ebolowa', 'https://commons.wikimedia.org/wiki/Special:FilePath/Carrefour_An_2000.jpg'),
  ('Bipindi', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Bipindi_3828587.png'),
  ('Réserve de faune du Dja', 'https://commons.wikimedia.org/wiki/Special:FilePath/Dja_River_and_pirogue.JPG'),
  ('Parc national de Lobéké', 'https://commons.wikimedia.org/wiki/Special:FilePath/First_mirador_in_Lob%C3%A9k%C3%A9.jpg'),
  ('Bertoua', 'https://commons.wikimedia.org/wiki/Special:FilePath/Plaque_Bertoua.jpg'),
  ('Yokadouma', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Route_de_Yokadouma.jpg/960px-Route_de_Yokadouma.jpg'),
  ('Lomié', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Lomi%C3%A9_crossroads.jpg/960px-Lomi%C3%A9_crossroads.jpg'),
  ('Villages Baka du sud-est', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Baka_dancers_June_2006.jpg'),
  ('Garoua-Boulaï', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Mosqu%C3%A9e_%2828604170443%29.jpg/960px-Mosqu%C3%A9e_%2828604170443%29.jpg'),
  ('Palais du Lamido de Ngaoundéré', 'https://commons.wikimedia.org/wiki/Special:FilePath/King''s_palace_Ngaoundere.PNG'),
  ('Grande Mosquée du Lamido de Ngaoundéré', 'https://commons.wikimedia.org/wiki/Special:FilePath/LamidoGrandMosque.jpg'),
  ('Lac Tison', 'https://commons.wikimedia.org/wiki/Special:FilePath/Le_lac_de_cratère_de_Tizon_à_Ngaoundéré.jpg'),
  ('Chutes de la Vina', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Madera_County_California_Incorporated_and_Unincorporated_areas_La_Vina_Highlighted_0640872.svg/960px-Madera_County_California_Incorporated_and_Unincorporated_areas_La_Vina_Highlighted_0640872.svg.png'),
  ('Chutes de Tello', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Chute_de_Tello_18.jpg/960px-Chute_de_Tello_18.jpg'),
  ('Chutes de Lancrenon', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Chutes_de_Lancrenon_%C3%A0_Yamba1.jpg/960px-Chutes_de_Lancrenon_%C3%A0_Yamba1.jpg'),
  ('Parc national du Mbam et Djerem', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cameroon_physical_map.svg/960px-Cameroon_physical_map.svg.png'),
  ('Ranch de Ngaoundaba', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Le_lac_de_N%27Gaoundaba_pr%C3%A8s_de_Ngaound%C3%A9r%C3%A9.jpg/960px-Le_lac_de_N%27Gaoundaba_pr%C3%A8s_de_Ngaound%C3%A9r%C3%A9.jpg'),
  ('Parc national de la Bénoué', 'https://commons.wikimedia.org/wiki/Special:FilePath/Benoue_National_park_hippo.jpg'),
  ('Parc national de Bouba Ndjida', 'https://commons.wikimedia.org/wiki/Special:FilePath/Babouin_olive_(Papio_anubis)_au_Parc_National_de_Bouba_Ndjidda,_Cameroun.jpg'),
  ('Parc national du Faro', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Cameroon_physical_map.svg/960px-Cameroon_physical_map.svg.png'),
  ('Grand marché de Garoua', 'https://commons.wikimedia.org/wiki/Special:FilePath/Marche_Garoua_Nord_Cameroon.jpg'),
  ('Lac et barrage de Lagdo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Lagdo_Dam.jpg/960px-Lagdo_Dam.jpg'),
  ('Lamidat de Rey Bouba', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Lamidat_de_Rey-Bouba_en_janvier_1974.jpg/960px-Lamidat_de_Rey-Bouba_en_janvier_1974.jpg'),
  ('Grande mosquée de Garoua', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg/960px-Yaound%C3%A9_Palais_des_Congr%C3%A8s.jpg'),
  ('Parc national de Waza', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bain_des_éléphants,_parc_de_Waza,_Nord_Cameroun_(25963018142).jpg'),
  ('Rhumsiki et le Pic de Kapsiki', 'https://commons.wikimedia.org/wiki/Special:FilePath/Rhumsiki_peak,_North_Cameroon_(25989204581).jpg'),
  ('Cases obus de Pouss', 'https://commons.wikimedia.org/wiki/Special:FilePath/Cam0505_Habitation_de_Pouss_Case_obus.jpg'),
  ('Lac de Maga', 'https://commons.wikimedia.org/wiki/Special:FilePath/Lac_de_Maga_dans_l''extrême_nord1.jpg'),
  ('Palais du Lamido de Maroua', 'https://commons.wikimedia.org/wiki/Special:FilePath/Danse_traditionnelle_chez_le_Lamido_de_Maroua.jpg'),
  ('Grand marché de Maroua', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/VUE_DE_MAROUA_DU_MONT_MAYO_IB%C3%89_%28EXTR%C3%8AME-NORD_CAMEROUN%29.jpg/960px-VUE_DE_MAROUA_DU_MONT_MAYO_IB%C3%89_%28EXTR%C3%8AME-NORD_CAMEROUN%29.jpg'),
  ('Dent de Mindif', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Pic_Mindif3.jpg/960px-Pic_Mindif3.jpg'),
  ('Mokolo', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Zbi%C3%B3r_prosa_z_pola_-_Mokolo_-_001954s.jpg/960px-Zbi%C3%B3r_prosa_z_pola_-_Mokolo_-_001954s.jpg'),
  ('Marché de Mora', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Hotel_de_ville_de_Mora.jpg/960px-Hotel_de_ville_de_Mora.jpg'),
  ('Village de cases de Yagoua', 'https://commons.wikimedia.org/wiki/Special:FilePath/Village_de_Cases_Yagoua.jpg'),
  ('Palais Royal des Rois Bamoun (Foumban)', 'https://commons.wikimedia.org/wiki/Special:FilePath/Bamun_sultan_palace.jpg'),
  ('Village des Artisans de Foumban', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Festival Nguon (Foumban)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Grande Mosquee de Foumban', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sultanat_de_Foumban.JPG/960px-Sultanat_de_Foumban.JPG'),
  ('Chefferie Bandjoun', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/La_r%C3%A9sidence_%28Renov%C3%A9e%29_de_l%27ancien_roi_Nie_KAMGA_Joseph_avant_dernier_chef_Bandjoun.JPG/960px-La_r%C3%A9sidence_%28Renov%C3%A9e%29_de_l%27ancien_roi_Nie_KAMGA_Joseph_avant_dernier_chef_Bandjoun.JPG'),
  ('Palais des Fons de Nso (Kumbo)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Tobin_View_of_the_Cathedral.JPG/960px-Tobin_View_of_the_Cathedral.JPG'),
  ('La Nouvelle Liberte (Douala)', 'https://commons.wikimedia.org/wiki/Special:FilePath/Statue_de_la_nouvelle_liberte_Douala.jpg'),
  ('Basilique Marie-Reine-des-Apotres de Mvolye (Yaounde)', 'https://commons.wikimedia.org/wiki/Special:FilePath/Int%C3%A9rieur_Basilique_Marie-Reine_des_ap%C3%B4tres_de_Mvoly%C3%A9_2.jpg'),
  ('Cathedrale Notre-Dame-des-Victoires (Yaounde)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Cath%C3%A9drale_Notre-Dame_Yaound%C3%A9.jpg/960px-Cath%C3%A9drale_Notre-Dame_Yaound%C3%A9.jpg'),
  ('Musee d''Art Camerounais (Mont Febe, Yaounde)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/B%C3%A2timent_du_mus%C3%A9e_des_B%C3%A9n%C3%A9dictins.jpg/960px-B%C3%A2timent_du_mus%C3%A9e_des_B%C3%A9n%C3%A9dictins.jpg'),
  ('Ngog Lituba (rocher sacre Bassa)', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Coucher_de_soleil_%C3%A0_Tayap.JPG/960px-Coucher_de_soleil_%C3%A0_Tayap.JPG'),
  ('Ancien Palais du Gouverneur allemand (Buea)', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Silicon_Mountain_as_seen_in_Buea%2C_Cameroon_on_26-06-2019.jpg'),
  ('Cathedrale Sainte-Anne-et-Saint-Joachim d''Ebolowa', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Cath%C3%A9drale_d%27Abang.jpg/960px-Cath%C3%A9drale_d%27Abang.jpg'),
  ('Villages Baka de Lomie', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Lomi%C3%A9_crossroads.jpg/960px-Lomi%C3%A9_crossroads.jpg'),
  ('id', 'longitude')
) AS d(name, image_url)
WHERE lower(t.name) = lower(d.name) AND (t.image_url IS NULL OR t.image_url = '');

SELECT region, count(*) AS places, count(image_url) AS with_photo
FROM tourism_places GROUP BY region ORDER BY region;
